[package]
name = "peggy"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "cli",
  "wallet",
  "miner",
  "actor",
  "rpc",
]

[[bin]]
name = "peggy-cli"
path = "peggy/main.rs"

[dependencies]
tokio = "1.22.0"

[workspace.dependencies]
cli      = { path = "./cli" }
wallet   = { path = "./wallet" }
miner    = { path = "./miner" }
rpc      = { path = "./rpc" }

[dependencies.cli]
workspace = true
