[package]
name = "peggy"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "cli",
  "wallet",
  "miner",
  "actor",
  "rpc",
  "state",
  "logger",
  "mpool",
  "gasestimator",
  "send",
]

[[bin]]
name = "peggy"
path = "peggy/main.rs"

[dependencies.tokio]
version = "1.22.0"
features = ["macros"]

[workspace.dependencies]
cli          = { path = "./cli" }
wallet       = { path = "./wallet" }
miner        = { path = "./miner" }
rpc          = { path = "./rpc" }
state        = { path = "./state" }
logger       = { path = "./logger" }
mpool        = { path = "./mpool" }
gasestimator = { path = "./gasestimator" }
send         = { path = "./send" }

[dependencies.cli]
workspace = true
