[package]
name = "peggy"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "cli",
  "wallet",
  "miner",
  "actor",
]

[[bin]]
name = "peggy-cli"
path = "peggy/main.rs"

[dependencies.peggy-cli]
path = "./cli"

