[package]
name = "actor"
version = "0.1.0"
edition = "2021"

[dependencies.fil_actor_init]
workspace = true

[dependencies.git2]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.anyhow]
workspace = true
