[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
serde_json = "1.0.88"

[dependencies.forest_key_management]
version = "0.2.0"
git = "https://github.com/ChainSafe/forest.git"

[dependencies.fvm_shared]
version = "2.0.0"
features = [ "arb" ]
