[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies.thiserror]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.clap]
workspace = true

[dependencies.cli]
workspace = true
