name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: fil-peggy - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y protobuf-compiler libprotobuf-dev build-essential clang ocl-icd-opencl-dev
      - uses: actions/checkout@v3
      - run: cd peggy; rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cd peggy; cargo build --verbose
      - run: cd peggy; cargo test --verbose
